### ISSUE TITLE
[PE-D][Tester C] Graphing bug for rating

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T15-1/tp#196]
![image.png](https://raw.githubusercontent.com/TanPingZhi/ped/main/files/188c2ae5-fd3b-4223-9935-31542135c551.png)

# Problem:
The time is not in the right order in the x axis

# To replicate this
1. Rate a person
2. Change local time to a date in the past
3. Rate the person again

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: TanPingZhi/ped#4

**Comment by kevinchangjk** [comment]
Likely due to the fact that we use `ArrayList` to store the ratings.

Then again, we kinda agreed that the ordering of the ratings has to be chronologically ordered since addition of rates has to be done through the `LocalDate::now` method.

Though, now that I think about it, it is possible to manually edit the ratings timestamps in the json file.

@Kok-je what do you think?

**Comment by Kok-je** [comment]
@kevinchangjk Yea, it is the way we store the ratings and timestamps in the json file. Can we make it uneditable by the users?

**Comment by kevinchangjk** [comment]
Wow, that kinda seems difficult to enforce though. Like it would be hard to stop them from editing the json file. If not, we could always just use a priority queue, similar to the way we store leave periods.

**Comment by Kok-je** [comment]
is it possible to sort an arraylist by localtime order, so we keeping calling sort everytime the graph is displayed

**Comment by kevinchangjk** [comment]
Yes.

**Comment by Kok-je** [comment]
Solved
