### ISSUE TITLE
[PE-D][Tester D] Employee ID increments when `add` Command fails due to integer overflow in the Leave field

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T15-1/tp#205]
![image.png](https://raw.githubusercontent.com/TheSoggy/ped/main/files/06d6ea90-b6e1-4b91-8a65-32d55d8582f9.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: TheSoggy/ped#12

**Comment by kevinchangjk** [comment]
This is in fact a subset of a more generalisable bug.

`add` command increments employee ID whenever an optional field is incorrectly given.

<img width="438" alt="image" src="https://user-images.githubusercontent.com/78629832/198824921-24c5918e-227f-4328-b2a3-ff5389fe866e.png">

From the above, we see that `employeeId = new EmployeeId()` is called (which increments the ID) after the mandatory fields are parsed. So an invalid department is fine, for example, but if there is an invalid phone number, then the ID is already incremented regardless.

A simple fix would be to move that line to right before the creation of the `Person` object near the return statement, because the error catching blocks are working fine.
